const swaggerUi = require("swagger-ui-express");
const swaggerJsDoc = require("swagger-jsdoc");
// const api = require("../api/index");
const option = {
    definition: {
        openapi: '3.0.0', // Specification (optional, defaults to swagger: '2.0')
        info:{
            title: "Todo API",
            version: '1.0.0',
            description: "Todo Express API with autogenerated swagger doc"
        },
        basePath: '/'
    },
    apis:["./api/**.js", "./auth/*.js"]
};
const specs = swaggerJsDoc(option);
module.exports = app =>{
    app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(specs));
};